### ISSUE TITLE
EmmentalModel has no attribute 'save_preds_to_numpy'

### ISSUE THREAD

**Issue by Rubenvdwaerden1997** [sarahmhooper/Medallion#2]
Dear Sarah,

Nice paper you worked on!
I had a question, I came across some previous issues, which i fixed by changing the setup.py file to the following, and made some changes in the code itself:
setup(
    name="Medallion",
    version="3.0.0",
    description=(
        "Training segmentation models with less labeled data."
    ),
    install_requires=[
        "emmental==0.1.1",
        "torch==1.9.0",
        "torchvision==0.10.0",
        "matplotlib>=3.3.4",
        "scikit-image>=0.17.2",
        "seaborn>=0.11.1",
        "urllib3==1.26.12",
        "pyyaml==5.3.1",
        "setuptools==59.5.0"
    ],
    python_requires=">=3.8",
    scripts=["bin/image_segmentation"],
    packages=find_packages(),
)
Now i come accross the issue that save_preds_to_numpy is not present in the current emmentalmodel class. Is there an easy way to fix this issue.
Traceback (most recent call last):
  File "\\medallion\dauphin\image_segmentation\image_segmentation.py", line 124, in main
    model.save_preds_to_numpy(dl,res_filename,KEY_DELIMITER)
AttributeError: 'EmmentalModel' object has no attribute 'save_preds_to_numpy'

By keeping the setup.py file as it was, it gave lots of issues with versioning, so that is the reason why I am trying to work around that.

Thank you in advance!

**Comment by sarahmhooper** [comment]
Hi, thanks for your comment. Emmental is maintained by a different author (Sen Wu), and all of this was written at least a few years ago, so I'm not surprised there are versioning issues---thanks for trying to work through it. 

For the specific function you're asking about, I think it is due to the version of Emmental you are installing in your modified code. This Medallion codebase needs to run off a specific branch of Emmental called online_score, found here: https://github.com/senwu/emmental/tree/sen/online_score. I still see save_preds_to_numpy in the model class of the online_score branch (here: https://github.com/senwu/emmental/blob/sen/online_score/src/emmental/model.py#L565), so if you get the right version of Emmental installed, I think it should solve this issue.

**Comment by Rubenvdwaerden1997** [comment]
I encountered some unsolvable issues with the 'online_score' branch due to versioning conflicts. However, I managed to find a workaround. Thank you for your quick response, though!

**Comment by sarahmhooper** [comment]
Oh I see. From what I recall, the primary difference between the main branch of Emmental and the online_score branch was how it handled predictions. The main branch of Emmental stored all predictions in memory before computing scores. This is okay for tasks like classification where predictions are small, but for tasks like segmentation can cause memory and runtime issues. The online_score branch instead updated a running score each iteration and didn't store all predictions in memory. It seems like Sen has included an "online_eval" arg in the config for Emmental. It looks like it is False by default, but you could set it to True and hopefully you won't run into the memory issues that were in the main branch a few years ago.
